s-y-yu/Pulsar

server/pulsar/.gitignore
server/pulsar/src/main/java/com/hammer/pulsar/config/DBConfig.java
server/pulsar/src/main/java/com/hammer/pulsar/config/WebConfig.java
server/pulsar/src/main/resources/application.properties

- Spring Web MVC 설정을 위한 WebConfig 클래스 생성
- MyBatis 및 Database 연결을 위한 DBConfig 클래스 생성
- DB 관련 application.properties 설정 수정

feat: Spring Boot 설정 추가

---

server/pulsar/src/main/java/com/hammer/pulsar/dao/ArticleDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/ArticleTagDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/BookmarkDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/CommentDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/ConcernDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/ExerciseDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/LikeDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/MemberDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/RoutineDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/TagDao.java

- 접근할 필요가 있는 모든 테이블에 대해 DAO 인터페이스 초기 구현 완료
- 이후에 DAO 인터페이스 수정사항 발생 가능
- 인터페이스 변경 등으로 인한 DTO 클래스 추가 및 수정사항 발생 가능

feat: DAO 인터페이스 초기 구현 완료

---

server/pulsar/src/main/java/com/hammer/pulsar/dto/NotDetermined.java
server/pulsar/src/main/java/com/hammer/pulsar/service/ArticleService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/InteractionService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/RoutineService.java

- 각 도메인의 서비스마다 인터페이스 초기 구현 완료
- 서비스의 세부 로직은 클래스 구현 단계에서 추가할 예정
- 메서드의 반환형과 파라미터에 어떻게 데이터를 주고 받을지 못 정했을 때 사용할 NotDetermined 클래스 추가

feat: 서비스 인터페이스 초기 구현 완료

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/CommunityController.java
server/pulsar/src/main/java/com/hammer/pulsar/controller/MemberRestController.java
server/pulsar/src/main/java/com/hammer/pulsar/controller/RoutineController.java

- API 문서에 기반해 각 컨트롤러 클래스 초기 구현 완료
- 메서드 세부 로직 구현 및 주석은 서비스 레이어 클래스 구현이 끝나면 시작 예정
- 예외 발생 시 Http 상태 응답에서 코드 중복을 줄일 방법 탐색 중

feat: 도메인별 컨트롤러 클래스 초기 구현 완료

---

client/src/core/api/axiosConfig.js

/core/api/axiosConfig.js
에서 확인할 수 있습니다.

feat: API call을 위한 axios 설정 작성

---

client/package.json
client/src/assets/css/init.css
client/src/assets/css/root.css
client/src/assets/css/typography.css
client/src/core/App.vue
client/src/core/components/Header/TheHeader.vue
client/src/core/components/Nav/TheNav.vue
client/src/core/components/layout/AboutBtn.vue
client/src/core/components/layout/AboutContent.vue
client/src/core/components/layout/TheLayout.vue
client/src/module/common/Btn.vue

- 초기화를 위한 init.css, 변수 저장을 위한 root.css, 폰트 설정을 위한 typography.css로 나뉘어 있습니다.
- Layout 안에는 TheLayout이라는 전역 레이아웃 뷰가 있고, 팀 소개를 위한 AboutBtn/AboutContent 컴포넌트가 있습니다.
- 나머지 디렉토리 안에는 TheLayout에서 Import해서 사용하는 Header, Nav 컴포넌트가 있습니다.

feat: Layout, Router-view의 조건부 렌더링 작성

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/MemberRestController.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/CommentDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/ConcernDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/LikeDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/MemberDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/article/CommentedArticle.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/common/ConcernRegistRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/common/ConcernUpdateRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/member/Member.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/member/MemberModifyForm.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/member/MemberModifyRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/member/MemberRegistRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/service/FileManagementService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberServiceImpl.java

- 회원 정보 CRUD 기능 세부 로직 구현 완료
- 마이페이지 기능 세부 로직 구현 완료
- 관련 클래스 일부 수정
- 예외 추가, Optional 클래스 적용, 스트림 적용으로 추후 코드 변경될 수 있음

feat: 회원 서비스 로직 구현 완료

---

server/pulsar/src/main/java/com/hammer/pulsar/dao/ArticleDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/CommentDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/LikeDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/article/Article.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/article/CommentedArticle.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/common/Writer.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/interaction/Comment.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/interaction/CommentWriteRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/interaction/Like.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/interaction/LikeRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/service/InteractionService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/InteractionServiceImpl.java

- 추천 서비스에 필요한 세부 로직 구현 완료
- 댓글 서비스에 필요한 세부 로직 구현 완료
- DTO 클래스 추가에 따른 패키지 구조 변경

feat: 사용자 인터랙션 서비스 로직 구현 완료

---

server/pulsar/src/main/java/com/hammer/pulsar/dao/ArticleDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/ArticleTagDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/article/Article.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/article/ArticleModifyForm.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/article/ArticleTagUpdateRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/service/ArticleService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/ArticleServiceImpl.java
server/pulsar/src/main/java/com/hammer/pulsar/service/FileManagementService.java

- 게시글 CRUD 기능 구현 완료
- 검색 메서드 삭제 (게시글 목록 조회 메서드로 합칠 예정)

feat: 게시글 서비스 로직 구현 완료

---

server/pulsar/src/main/java/com/hammer/pulsar/dao/RoutineDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/routine/RoutineModifyRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/routine/RoutineRegistRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/service/RoutineService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/RoutineServiceImpl.java

- 루틴 CRUD 기능 로직 구현 완료
- API 수정으로 인한 운동 세부 계획 CUD 로직 삭제

feat: 루틴 서비스 로직 구현 완료

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/MemberRestController.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberServiceImpl.java

- 회원 컨트롤러의 메서드 구현 완료
- API 문서와 일치하는 HTTP 상태 응답코드 작성 완료
- 에러코드는 추후 인터셉트 구현 시 작성 예정

feat: 회원 기능 컨트롤러 구현 완료

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/RoutineRestController.java

- 루틴 컨트롤러 클래스명 변경하여 JSON 형식으로 응답한다는 것을 강조
- 루틴 컨트롤러의 메서드 구현 완료
- 운동 세부 계획 API가 삭제됨에 따라 관련 메서드 삭제

feat: 루틴 기능 컨트롤러 구현 완료

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/CommunityRestController.java

- 커뮤니티 컨트롤러의 메서드 구현 완료
- API 문서와 일치하는 HTTP 상태 응답코드 작성 완료

feat: 커뮤니티 기능 컨트롤러 구현 완료

---

server/pulsar/src/main/resources/mappers/memberMapper.xml

api 테스트를 위한 memberMapper.xml을 작성

feat: memberMapper.xml 작성

---

db/pulsar.sql

- api 테스트에 필요한 Pulsar 데이터베이스 초기 설계 DDL 파일
- 추후에 TB_ROUTINE에 요일 COLUMN 추가할 예정

feat: Pulsar 데이터베이스 초기 설계 DDL

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/MemberRestController.java
server/pulsar/src/main/java/com/hammer/pulsar/handler/GlobalExceptionHandler.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberServiceImpl.java
server/pulsar/src/main/resources/application.properties
server/pulsar/src/main/resources/mappers/memberMapper.xml

- application.propeties의 datasource 설정의 구문 오류 수정 ( ${ } 추가 )
- 로직 수정 시 디버깅을 위한 패키지 전역의 debug 레벨 로거 설정
- 회원 가입, 조회, 삭제 상황에서 발생할 수 있는 예외의 처리
- 컨트롤러의 누락된 어노테이션 추가
- 컨트롤러 전역에서 발생하는 예외를 처리할 GlobalExceptionHandler 추가

fix: 회원 API 오류 일부 수정

---

server/pulsar/src/main/resources/mappers/articleTagMapper.xml
server/pulsar/src/main/resources/mappers/concernTagMapper.xml

mybatis 구문 오류로 DI에 실패해 애플리케이션 실행이 안되던 문제를 수정

fix: mapper.xml mybatis 구문 오류 수정

---

client/src/core/App.vue
client/src/core/store/actions.js
client/src/core/store/getters.js
client/src/core/store/index.js
client/src/core/store/mutations.js
client/src/core/store/state.js
client/src/module/common/SquareButton.vue
client/src/module/common/TextInput.vue
client/src/module/landing/LandingView.vue
client/src/module/landing/components/LoginContainer.vue
client/src/module/landing/components/LoginContent.vue
client/src/module/landing/components/WelcomePulsar.vue
client/src/module/landing/router/landing.js

feat: vuex 설정 및 로그인 시 vuex에 데이터가 전달되도록 조정

---

client/src/core/components/Header/TheHeader.vue
client/src/core/components/Nav/TheNav.vue
client/src/module/common/CommunityList.vue
client/src/module/common/TagItem.vue
client/src/module/common/TextInput.vue
client/src/stories/assets/layout/TheHeader.stories.js
client/src/stories/assets/layout/TheNav.stories.js
client/src/stories/common/CommunityList.stories.js
client/src/stories/common/RoundButton.stories.js
client/src/stories/common/RoutineList.stories.js
client/src/stories/common/SquareButton.stories.js
client/src/stories/common/TagItem.stories.js
client/src/stories/common/TextInput.stories.js

이것저것 버그를 수정합니다.
css 경로가 잘못되어서 인식하지 못하던 문제들을 해결하고,
제작한 컴포넌트를 storybook에 추가했습니다.

fix: 버그 수정

---

server/pulsar/src/main/java/com/hammer/pulsar/config/WebConfig.java
server/pulsar/src/main/java/com/hammer/pulsar/controller/MemberRestController.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/MemberDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/member/LoginForm.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/member/LoginInfo.java
server/pulsar/src/main/java/com/hammer/pulsar/exception/UnauthorizedException.java
server/pulsar/src/main/java/com/hammer/pulsar/handler/GlobalExceptionHandler.java
server/pulsar/src/main/java/com/hammer/pulsar/interceptor/AuthCheckInterceptor.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberServiceImpl.java
server/pulsar/src/main/resources/mappers/concernTagMapper.xml
server/pulsar/src/main/resources/mappers/memberMapper.xml

- 로그인에 필요한 DTO 클래스 추가
- memberMapper.xml, concernTagMapper.xml 변경
- 인증 실패 런타임 예외 클래스 추가
- UnauthorizedException 핸들러 추가
- 로그인 회원정보를 처리하기 위한 인터셉터 추가

feat: 로그인/로그아웃 기능 구현

---

client/src/core/api/axiosConfig.js

axiosConfig에 관련 헤더를 추가합니다.
그런데 *로 해결한 것이어서 추후 수정이 필요합니다.

fix: cors 관련 설정 추가

---

server/pulsar/src/main/java/com/hammer/pulsar/config/WebConfig.java
server/pulsar/src/main/java/com/hammer/pulsar/interceptor/AuthCheckInterceptor.java

- API 테스트에서 CORS 문제 해결을 위해 임시로 CorsMapping 설정

feat: API 테스트시 CORS 문제 해결을 위한 임시 CorsMapping 설정

---

server/pulsar/src/main/java/com/hammer/pulsar/dao/ArticleDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/CommentDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/LikeDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/article/CommentedArticle.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/member/MemberRegistRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberServiceImpl.java
server/pulsar/src/main/resources/mappers/articleMapper.xml
server/pulsar/src/main/resources/mappers/articleTagMapper.xml
server/pulsar/src/main/resources/mappers/commentMapper.xml
server/pulsar/src/main/resources/mappers/concernTagMapper.xml
server/pulsar/src/main/resources/mappers/exerciseMapper.xml
server/pulsar/src/main/resources/mappers/likeMapper.xml
server/pulsar/src/main/resources/mappers/memberMapper.xml
server/pulsar/src/main/resources/mappers/tagMapper.xml

- 마이페이지 기능에 필요한 내 활동 내역 API 구현
- 기존 회원 CRUD API에 고민 태그도 같이 변동되도록 수정

feat: 마이페이지 관련 API 기능 및 세부 수정

---

client/src/core/api/axiosConfig.js
client/src/module/landing/components/SignupContainer.vue
client/src/module/landing/components/SignupContent.vue

- 요청 형식을 수정합니다
- json 대신 Multipart/form-data로 보냅니다

fix: signup bugfix

---

client/src/core/api/axiosConfig.js
client/src/core/api/community.js
client/src/core/api/member.js
client/src/core/api/routine.js
client/src/core/components/Header/TheHeader.vue
client/src/core/store/actions.js
client/src/core/store/getters.js
client/src/core/store/mutations.js
client/src/core/store/state.js
client/src/module/landing/components/LoginContainer.vue

- 로그인, 로그아웃이 제대로 동작하면 됩니다
- vuex를 통해 sessionId가 제대로 들어오는지 확인하면 됩니다

feat: JWT 관련 테스트 코드 작성

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/RoutineRestController.java
server/pulsar/src/main/java/com/hammer/pulsar/util/UUIDTokenManager.java

- 요청 시 회원번호가 필요한 API에서 인증 정보로부터 로그인 회원의 회원번호를 조회하는 로직 추가

feat: 루틴 API 작성자 회원번호 조회 구현

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/CommunityRestController.java

- 요청 시 회원번호가 필요한 API에서 인증 정보로부터 로그인 회원의 회원번호를 조회하는 로직 추가

feat: 커뮤니티 API 작성자 회원번호 조회 구현

---

client/babel.config.js
client/package-lock.json
client/package.json
client/src/assets/css/typography.css
client/src/core/components/Header/TheHeader.vue
client/src/core/components/Nav/TheNav.vue
client/src/core/components/Nav/icons/CommunityIcon.vue
client/src/core/components/Nav/icons/MypageIcon.vue
client/src/core/components/Nav/icons/RoutinesIcon.vue
client/src/core/components/Nav/icons/StatisticsIcon.vue
client/src/module/common/RoundButton.vue
client/src/module/common/SquareButton.vue
client/src/module/landing/components/LoginContainer.vue
client/src/module/landing/components/LoginContent.vue
client/src/module/landing/components/SignupContent.vue
client/src/module/landing/components/WelcomePulsar.vue
client/vue.config.js
client/webpack.config.js

제대로 작동합니다.
- 현재 라우트 주소에 따라 아이콘이 켜지고 꺼집니다
- 그 외 이미지 문제 해결을 위해 의존성 설정을 바꾸거나 의존성을 추가/제거한 부분이 있습니다
- 자잘한 css 수정도 있습니다

feat: Nav 컴포넌트 추가

---

client/src/core/api/axiosConfig.js
client/src/core/api/community.js
client/src/core/api/member.js
client/src/core/api/routine.js
client/src/core/store/actions.js
client/src/core/store/getters.js
client/src/core/store/mutations.js
client/src/core/store/state.js

fix: sessionId를 token으로 표현만 수정

fix: sessionId를 token으로 표현만 수정

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/CommunityRestController.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/ArticleDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/CommentDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/LikeDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/article/Article.java
server/pulsar/src/main/java/com/hammer/pulsar/service/ArticleService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/ArticleServiceImpl.java
server/pulsar/src/main/java/com/hammer/pulsar/service/InteractionService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/InteractionServiceImpl.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberServiceImpl.java
server/pulsar/src/main/resources/mappers/articleMapper.xml
server/pulsar/src/main/resources/mappers/commentMapper.xml
server/pulsar/src/main/resources/mappers/likeMapper.xml

- 커뮤니티 API에 401, 403 응답 추가
- 글 상세보기에서 누락된 정보를 추가

feat: 커뮤니티 API 응답 추가

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/CommunityRestController.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/article/ArticleModifyRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/article/ArticleWriteRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/service/ArticleServiceImpl.java
server/pulsar/src/main/resources/mappers/articleMapper.xml
server/pulsar/src/main/resources/mappers/articleTagMapper.xml
server/pulsar/src/main/resources/mappers/commentMapper.xml

- 게시글 작성 / 수정 구현
- 댓글 작성 / 삭제 구현

feat: 커뮤니티 API 구현

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/MemberRestController.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/member/MemberModifyResponse.java
server/pulsar/src/main/java/com/hammer/pulsar/exception/DuplicateValueException.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberServiceImpl.java
server/pulsar/src/main/resources/mappers/articleTagMapper.xml
server/pulsar/src/main/resources/mappers/concernTagMapper.xml
server/pulsar/src/main/resources/mappers/memberMapper.xml

feat: 회원정보 수정 기능 구현

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/RoutineRestController.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/RoutineDetailDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/routine/ExerciseRegistRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/routine/RoutineModifyRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/service/RoutineServiceImpl.java
server/pulsar/src/main/resources/mappers/routineDetailMapper.xml
server/pulsar/src/main/resources/mappers/routineMapper.xml

feat: 루틴 수정 기능 구현

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/TagController.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/ExerciseDao.java
server/pulsar/src/main/java/com/hammer/pulsar/service/TagService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/TagServiceImpl.java
server/pulsar/src/main/resources/mappers/exerciseMapper.xml

- 게시글, 고민 태그 목록을 조회하는 기능 구현
- 운동 목록을 조회하는 기능 구현

feat: 태그 목록 조회 기능 구현

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/CommunityRestController.java
server/pulsar/src/main/java/com/hammer/pulsar/dao/ArticleDao.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/article/ArticleWriteRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/article/PaginationCriteria.java
server/pulsar/src/main/java/com/hammer/pulsar/service/ArticleService.java
server/pulsar/src/main/java/com/hammer/pulsar/service/ArticleServiceImpl.java
server/pulsar/src/main/resources/mappers/articleMapper.xml

- 선택한 태그를 포함하는 게시글 목록만 조회하는 검색 기능 구현
- 게시글 고유번호 역순(최신순)으로 게시글 목록을 반환
- 커서 방식으로 페이지네이션 구현

feat: 게시글 목록 조회시 검색 및 페이지네이션 구현

---

server/pulsar/src/main/java/com/hammer/pulsar/config/WebConfig.java
server/pulsar/src/main/java/com/hammer/pulsar/controller/CommunityRestController.java
server/pulsar/src/main/java/com/hammer/pulsar/interceptor/AuthCheckInterceptor.java

feat: 인터셉터 매핑 경로 설정

---

client/src/assets/css/init.css
client/src/assets/css/typography.css
client/src/core/api/axiosConfig.js
client/src/core/components/Nav/TheNav.vue
client/src/module/common/CommunityList.vue
client/src/module/common/ExerciseList.vue
client/src/module/common/ModalView.vue
client/src/module/common/RoundButton.vue
client/src/module/common/SquareButton.vue
client/src/module/common/TagForm.vue
client/src/module/common/TextInput.vue
client/src/module/landing/components/LoginContent.vue
client/src/module/landing/components/SignupContent.vue
client/src/module/routines/components/RoutineDetailContainer.vue
client/src/module/routines/components/RoutineDetailContent.vue
client/src/module/routines/components/RoutineListContainer.vue
client/src/module/routines/components/RoutineListContent.vue
client/src/module/routines/components/RoutineModifyContainer.vue
client/src/module/routines/router/routines.js
client/src/stories/common/Modalview.stories.js
client/src/stories/common/TheNav.stories.js

루틴 리스트 조회, 루틴 상세 조회, 루틴 추가 구현 완료
- 공통 컴포넌트 modal 구현 완료
- 그 외 많은 다른 디자인 변경점이 있습니다

feat: Routine 세부 기능 구현

---

client/src/module/community/CommunityView.vue
client/src/module/community/components/CommunityDetailContainer.vue
client/src/module/community/components/CommunityListContainer.vue
client/src/module/community/components/CommunityListContent.vue
client/src/module/community/router/community.js

feat: community 게시판 리스트 및 글 작성 구현 완료

---

client/src/core/api/community.js
client/src/core/store/index.js
client/src/module/common/CommentList.vue
client/src/module/common/ModalView.vue
client/src/module/common/TextInput.vue
client/src/module/community/components/CommunityDetailContainer.vue
client/src/module/community/components/CommunityDetailContent.vue
client/src/module/community/components/CommunityListContainer.vue
client/src/module/community/router/community.js
client/src/module/routines/components/RoutineDetailContent.vue

아래 기능을 추가합니다.
- 글 리스트 조회
- 상세조회
- 글 삭제
- 댓글 작성

feat: 커뮤니티 게시판 기능 추가

---

server/pulsar/src/main/java/com/hammer/pulsar/config/WebConfig.java

fix: CORS 오류 해결

---

client/src/module/common/TagForm.vue
client/src/module/community/components/CommunityDetailContainer.vue
client/src/module/landing/components/LoginContainer.vue
client/src/module/landing/components/SignupContainer.vue
client/src/module/landing/components/SignupContent.vue

공통 태그 컴포넌트를 구현했습니다.
그 외 통신 문제 관련 컴포넌트 디버깅을 했습니다.

feat: 태그 기능 추가 및 디버깅

---

client/src/module/common/ExerciseList.vue
client/src/module/common/TagForm.vue
client/src/module/common/TagItem.vue
client/src/module/community/components/CommunityDetailContainer.vue
client/src/module/landing/components/SignupContainer.vue
client/src/module/landing/components/SignupContent.vue

태그 선택 기능을 구현합니다. 상위 컴포넌트에서 데이터가 정상적으로 바인딩됩니다.

feat: 태그 선택 데이터 바인딩 구현

---

server/pulsar/src/main/java/com/hammer/pulsar/controller/CommunityRestController.java
server/pulsar/src/main/java/com/hammer/pulsar/dto/article/ArticleWriteRequest.java
server/pulsar/src/main/java/com/hammer/pulsar/interceptor/AuthCheckInterceptor.java
server/pulsar/src/main/java/com/hammer/pulsar/service/ArticleServiceImpl.java
server/pulsar/src/main/java/com/hammer/pulsar/service/MemberServiceImpl.java

빈 태그 목록을 추가하려고 할 때 NPE가 발생하는 오류를 수정했습니다.

fix: 태그 목록이 비어있을 때 NPE 처리
